"use client";

import { useState, useCallback } from "react";
import AppShell from "@/components/AppShell";
import { MOCK_LEAD_SHEET } from "@/lib/store";
import type { LeadSheet, ChordSymbol } from "@/types";

function chordDisplay(chord: ChordSymbol): string {
  return `${chord.root}${chord.quality}${chord.bass ? `/${chord.bass}` : ""}`;
}

async function generatePDF(sheet: LeadSheet): Promise<Blob> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text(sheet.title, pageWidth / 2, y, { align: "center" });
  y += 10;

  // Artist + metadata
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(
    `${sheet.artist}  |  Key: ${sheet.key}  |  ${sheet.timeSignature}  |  ${sheet.bpm} BPM`,
    pageWidth / 2,
    y,
    { align: "center" }
  );
  y += 12;

  // Divider
  doc.setDrawColor(180);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  const measuresPerRow = 4;
  const cellWidth = contentWidth / measuresPerRow;
  const cellHeight = 18;

  for (const section of sheet.sections) {
    // Check page overflow
    if (y + 14 + Math.ceil(section.measures.length / measuresPerRow) * cellHeight > 260) {
      doc.addPage();
      y = margin;
    }

    // Section name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(section.name, margin, y);
    y += 7;

    // Measures in rows of 4
    for (let row = 0; row < Math.ceil(section.measures.length / measuresPerRow); row++) {
      const measures = section.measures.slice(row * measuresPerRow, (row + 1) * measuresPerRow);

      for (let i = 0; i < measures.length; i++) {
        const m = measures[i];
        const x = margin + i * cellWidth;

        // Cell border
        doc.setDrawColor(200);
        doc.rect(x, y, cellWidth, cellHeight);

        // Chord symbols
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        const chordStr = m.chords.map(chordDisplay).join("  ");
        doc.text(chordStr, x + 3, y + 6);

        // Lyrics
        if (m.lyrics) {
          doc.setFont("helvetica", "italic");
          doc.setFontSize(9);
          doc.text(m.lyrics, x + 3, y + 13, { maxWidth: cellWidth - 6 });
        }
      }

      y += cellHeight;
    }

    y += 6;
  }

  // Footer
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by The Conductor — Harmonic Precision", pageWidth / 2, 268, {
    align: "center",
  });

  return doc.output("blob");
}

export default function LeadSheetPdfPage() {
  const [sheet] = useState<LeadSheet>(MOCK_LEAD_SHEET);
  const [generating, setGenerating] = useState(false);

  const handleExport = useCallback(async () => {
    setGenerating(true);
    try {
      const blob = await generatePDF(sheet);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${sheet.title.replace(/\s+/g, "_")}_Lead_Sheet.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } finally {
      setGenerating(false);
    }
  }, [sheet]);

  return (
    <AppShell
      headerActions={
        <button
          onClick={handleExport}
          disabled={generating}
          className="flex items-center gap-2 bg-primary text-on-primary px-5 py-2 rounded-xl text-sm font-bold hover:bg-primary-fixed-dim transition-all active:scale-95 shadow-lg shadow-primary/20 disabled:opacity-50"
        >
          <span className="material-symbols-outlined text-lg">
            {generating ? "hourglass_top" : "download"}
          </span>
          {generating ? "Generating..." : "Download PDF"}
        </button>
      }
    >
      <div className="pt-6 pb-24 px-8 max-w-5xl mx-auto w-full">
        {/* Preview Header */}
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-headline font-bold tracking-tight">PDF Preview</h2>
            <p className="text-sm text-outline mt-1">Review before exporting</p>
          </div>
          <button
            onClick={() => window.history.back()}
            className="flex items-center gap-2 text-sm text-outline hover:text-on-surface transition-colors"
          >
            <span className="material-symbols-outlined text-lg">arrow_back</span>
            Back to Editor
          </button>
        </div>

        {/* Paper Preview */}
        <div className="bg-white text-black rounded-lg shadow-2xl mx-auto max-w-3xl p-12 min-h-[800px]">
          {/* Title */}
          <h1 className="text-3xl font-bold text-center mb-2 font-serif">{sheet.title}</h1>
          <p className="text-center text-gray-600 mb-6 text-sm">
            {sheet.artist} &nbsp;|&nbsp; Key: {sheet.key} &nbsp;|&nbsp; {sheet.timeSignature} &nbsp;|&nbsp;{" "}
            {sheet.bpm} BPM
          </p>
          <hr className="mb-6 border-gray-300" />

          {/* Sections */}
          {sheet.sections.map((section) => (
            <div key={section.id} className="mb-8">
              <h3 className="font-bold text-base mb-3 text-gray-800 tracking-wide">{section.name}</h3>

              {/* Measure rows (4 per line) */}
              {Array.from({ length: Math.ceil(section.measures.length / 4) }).map((_, rowIdx) => (
                <div key={rowIdx} className="flex border border-gray-300 mb-[-1px]">
                  {section.measures.slice(rowIdx * 4, rowIdx * 4 + 4).map((measure) => (
                    <div
                      key={measure.id}
                      className="flex-1 border-r border-gray-300 last:border-r-0 px-3 py-2 min-h-[50px]"
                    >
                      <div className="font-bold text-sm mb-1">
                        {measure.chords.map(chordDisplay).join("  ")}
                      </div>
                      {measure.lyrics && (
                        <div className="text-xs text-gray-500 italic">{measure.lyrics}</div>
                      )}
                    </div>
                  ))}
                  {/* Fill empty cells */}
                  {rowIdx === Math.ceil(section.measures.length / 4) - 1 &&
                    section.measures.length % 4 !== 0 &&
                    Array.from({ length: 4 - (section.measures.length % 4) }).map((_, i) => (
                      <div key={`empty-${i}`} className="flex-1 border-r border-gray-300 last:border-r-0" />
                    ))}
                </div>
              ))}
            </div>
          ))}

          {/* Footer */}
          <p className="text-center text-gray-400 text-xs mt-12">
            Generated by The Conductor — Harmonic Precision
          </p>
        </div>
      </div>
    </AppShell>
  );
}
